name = "duckduckgo-ai"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

[dev]
ip = "127.0.0.1"

[vars]
API_KEY = "sk-1145141919810114514"

[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "f1d11acbd9604dc8a842e00e1501ae46"
